// Media_TranscodeX Web - FFmpeg.wasm Engine & Client-Side Transcoder

let worker = null;
let sourceFile = null;
let externalAudio = [];
let externalSubtitles = [];
let includeOriginalAudio = true;
let mediaDuration = 0;

// DOM Elements
const dropzone = document.getElementById('dropzone');
const fileInput = document.getElementById('fileInput');
const infoTree = document.getElementById('infoTree');
const outputFileNameInput = document.getElementById('outputFileNameInput');
const formatSelect = document.getElementById('formatSelect');
const resSelect = document.getElementById('resSelect');
const customResGroup = document.getElementById('customResGroup');
const widthInput = document.getElementById('widthInput');
const heightInput = document.getElementById('heightInput');
const bitrateSelect = document.getElementById('bitrateSelect');
const audioBitrateSelect = document.getElementById('audioBitrateSelect');
const muteAudioCheck = document.getElementById('muteAudioCheck');
const trackList = document.getElementById('trackList');
const addAudioBtn = document.getElementById('addAudioBtn');
const addSubBtn = document.getElementById('addSubBtn');
const audioFileInput = document.getElementById('audioFileInput');
const subFileInput = document.getElementById('subFileInput');
const startBtn = document.getElementById('startBtn');
const downloadBtn = document.getElementById('downloadBtn');
const progressBarFill = document.getElementById('progressBarFill');
const progressText = document.getElementById('progressText');
const statusMessage = document.getElementById('statusMessage');
const terminalLog = document.getElementById('terminalLog');
const outputVideo = document.getElementById('outputVideo');

// Logging helper
function log(msg, isError = false) {
    const div = document.createElement('div');
    div.textContent = `[${new Date().toLocaleTimeString()}] ${msg}`;
    if (isError) div.style.color = '#f43f5e';
    terminalLog.appendChild(div);
    terminalLog.scrollTop = terminalLog.scrollHeight;
}

// Initialize FFmpeg WebAssembly Worker (Zero CORS restrictions)
async function initFFmpeg() {
    if (worker) return true;
    try {
        log('Loading WebAssembly core modules (FFmpeg.wasm v0.11.6)...');
        statusMessage.textContent = 'Loading WebAssembly Core...';

        const { createWorker } = FFmpeg;
        worker = createWorker({
            corePath: 'https://unpkg.com/@ffmpeg/core@0.11.0/dist/ffmpeg-core.js',
            log: true,
            logger: m => {
                if (m && m.message) {
                    log(m.message);
                }
            },
            progress: p => {
                if (p && typeof p.ratio === 'number') {
                    const pct = Math.min(100, Math.max(0, Math.round(p.ratio * 100)));
                    progressBarFill.style.width = `${pct}%`;
                    progressText.textContent = `${pct}%`;
                    statusMessage.textContent = `Transcoding in progress... (${pct}%)`;
                }
            }
        });

        await worker.load();

        log('⚡ WebAssembly core successfully loaded and ready!');
        statusMessage.textContent = 'WebAssembly Engine Ready.';
        return true;
    } catch (err) {
        const errorText = (err && (err.message || err.toString())) ? (err.message || err.toString()) : String(err);
        log(`Failed to load WebAssembly core: ${errorText}`, true);
        statusMessage.textContent = `Error loading WebAssembly: ${errorText}`;
        console.error('FFmpeg Load Error:', err);
        return false;
    }
}

// Event Listeners for File Selection
dropzone.addEventListener('click', () => fileInput.click());
fileInput.addEventListener('change', (e) => handleFileSelect(e.target.files[0]));

dropzone.addEventListener('dragover', (e) => {
    e.preventDefault();
    dropzone.classList.add('dragover');
});

dropzone.addEventListener('dragleave', () => dropzone.classList.remove('dragover'));

dropzone.addEventListener('drop', (e) => {
    e.preventDefault();
    dropzone.classList.remove('dragover');
    if (e.dataTransfer.files.length > 0) {
        handleFileSelect(e.dataTransfer.files[0]);
    }
});

// Resolution Select Dropdown Toggle
resSelect.addEventListener('change', () => {
    if (resSelect.value === 'custom') {
        customResGroup.style.display = 'flex';
    } else {
        customResGroup.style.display = 'none';
    }
});

// Format Select Dropdown Change -> Auto Update Default Custom Output Name
formatSelect.addEventListener('change', () => {
    updateDefaultOutputFileName();
});

function updateDefaultOutputFileName() {
    if (!sourceFile) return;
    const baseName = sourceFile.name.substring(0, sourceFile.name.lastIndexOf('.')) || 'converted_media';
    if (!outputFileNameInput.value || outputFileNameInput.dataset.autoGenerated === 'true') {
        outputFileNameInput.value = `${baseName}_converted`;
        outputFileNameInput.dataset.autoGenerated = 'true';
    }
}

outputFileNameInput.addEventListener('input', () => {
    outputFileNameInput.dataset.autoGenerated = 'false';
});

// Handle Source File Inspection
async function handleFileSelect(file) {
    if (!file) return;
    sourceFile = file;
    log(`Selected file: ${file.name} (${(file.size / (1024 * 1024)).toFixed(2)} MB)`);

    // Set Default Output File Name
    outputFileNameInput.dataset.autoGenerated = 'true';
    updateDefaultOutputFileName();

    // Reset State & UI
    externalAudio = [];
    externalSubtitles = [];
    includeOriginalAudio = true;
    infoTree.innerHTML = '';
    downloadBtn.style.display = 'none';
    outputVideo.style.display = 'none';
    startBtn.disabled = false;

    renderTrackList();

    // Inspect Media using HTML5 Element & URL
    const url = URL.createObjectURL(file);
    const tempVideo = document.createElement('video');
    tempVideo.preload = 'metadata';
    tempVideo.src = url;

    tempVideo.onloadedmetadata = () => {
        mediaDuration = tempVideo.duration || 0;
        const width = tempVideo.videoWidth || 0;
        const height = tempVideo.videoHeight || 0;

        renderTreeItem('File Name', file.name);
        renderTreeItem('File Size', `${(file.size / (1024 * 1024)).toFixed(2)} MB`);
        renderTreeItem('Duration', `${mediaDuration.toFixed(2)} seconds`);

        if (width > 0 && height > 0) {
            renderTreeItem('Resolution', `${width} x ${height}`);
            renderTreeItem('Aspect Ratio', `${(width / height).toFixed(2)}:1`);
        }

        statusMessage.textContent = `Inspected: ${file.name}. Ready for transcode.`;
    };

    // Pre-load FFmpeg WebAssembly module
    initFFmpeg();
}

function renderTreeItem(key, val) {
    const div = document.createElement('div');
    div.className = 'tree-item';
    div.innerHTML = `<span class="tree-key">${key}:</span><span class="tree-val">${val}</span>`;
    infoTree.appendChild(div);
}

function renderTrackList() {
    trackList.innerHTML = '';

    // Primary Video Track
    const vDiv = document.createElement('div');
    vDiv.className = 'track-card';
    vDiv.innerHTML = `
        <div class="track-info">
            <span class="track-badge badge-video">VIDEO</span>
            <span>Primary Video Stream</span>
        </div>
    `;
    trackList.appendChild(vDiv);

    // Primary Audio Track (with toggle remove option)
    if (!muteAudioCheck.checked && includeOriginalAudio) {
        const aDiv = document.createElement('div');
        aDiv.className = 'track-card';
        aDiv.innerHTML = `
            <div class="track-info">
                <span class="track-badge badge-audio">AUDIO</span>
                <span>Primary Internal Audio Stream</span>
            </div>
            <button class="btn btn-secondary" style="padding: 4px 8px; font-size: 11px; color: var(--accent-rose);" onclick="removeOriginalAudio()">Remove</button>
        `;
        trackList.appendChild(aDiv);
    }

    // External Audio Tracks
    externalAudio.forEach((item, index) => {
        const div = document.createElement('div');
        div.className = 'track-card';
        div.innerHTML = `
            <div class="track-info">
                <span class="track-badge badge-audio">AUDIO</span>
                <span>Ext: ${item.file.name} (+${item.delaySec}s delay)</span>
            </div>
            <button class="btn btn-secondary" style="padding: 4px 8px; font-size: 11px; color: var(--accent-rose);" onclick="removeExternalAudio(${index})">Delete</button>
        `;
        trackList.appendChild(div);
    });

    // External Subtitle Tracks
    externalSubtitles.forEach((item, index) => {
        const div = document.createElement('div');
        div.className = 'track-card';
        div.innerHTML = `
            <div class="track-info">
                <span class="track-badge badge-subtitle">SUBTITLE</span>
                <span>Ext: ${item.file.name}</span>
            </div>
            <button class="btn btn-secondary" style="padding: 4px 8px; font-size: 11px; color: var(--accent-rose);" onclick="removeExternalSubtitle(${index})">Delete</button>
        `;
        trackList.appendChild(div);
    });
}

function removeOriginalAudio() {
    includeOriginalAudio = false;
    renderTrackList();
    log('Removed original audio track from transcode output.');
}

function removeExternalAudio(index) {
    externalAudio.splice(index, 1);
    renderTrackList();
    log('Removed external audio track.');
}

function removeExternalSubtitle(index) {
    externalSubtitles.splice(index, 1);
    renderTrackList();
    log('Removed external subtitle track.');
}

muteAudioCheck.addEventListener('change', () => {
    renderTrackList();
    if (muteAudioCheck.checked) {
        log('Mute Audio (-an) enabled: All audio tracks will be removed.');
    }
});

// Add External Audio
addAudioBtn.addEventListener('click', () => audioFileInput.click());
audioFileInput.addEventListener('change', (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const delayStr = prompt(`Enter Start Offset Delay (seconds) for external audio "${file.name}":`, '0');
    const delaySec = parseFloat(delayStr) || 0;

    externalAudio.push({ file, delaySec });
    renderTrackList();
    log(`Added external audio track: ${file.name} with ${delaySec}s offset`);
});

// Add External Subtitle
addSubBtn.addEventListener('click', () => subFileInput.click());
subFileInput.addEventListener('change', (e) => {
    const file = e.target.files[0];
    if (!file) return;

    externalSubtitles.push({ file });
    renderTrackList();
    log(`Added external subtitle track: ${file.name}`);
});

// Start Transcoding & Multiplexing Workflow
startBtn.addEventListener('click', async () => {
    if (!sourceFile) return;

    const isLoaded = await initFFmpeg();
    if (!isLoaded || !worker) {
        alert('WebAssembly engine failed to load. Check browser console or network connection.');
        return;
    }

    startBtn.disabled = true;
    progressBarFill.style.width = '0%';
    progressText.textContent = '0%';
    statusMessage.textContent = 'Preparing virtual filesystem and loading media...';

    try {
        // 1. Write Primary Source File to FFmpeg VFS
        const inputName = `input_${sourceFile.name.replace(/[^a-zA-Z0-9._-]/g, '_')}`;
        log(`Writing ${sourceFile.name} to WebAssembly memory...`);
        await worker.write(inputName, new Uint8Array(await sourceFile.arrayBuffer()));

        // 2. Prepare Output Extension & Options
        const targetExt = formatSelect.value;
        const customName = (outputFileNameInput.value || 'converted_media').trim().replace(/[^a-zA-Z0-9._-]/g, '_');
        const outputName = `${customName}.${targetExt}`;

        const args = ['-i', inputName];

        // 3. Handle External Audio Tracks
        for (let i = 0; i < externalAudio.length; i++) {
            const extAudio = externalAudio[i];
            const extAudioName = `audio_ext_${i}_${extAudio.file.name.replace(/[^a-zA-Z0-9._-]/g, '_')}`;
            await worker.write(extAudioName, new Uint8Array(await extAudio.file.arrayBuffer()));

            if (extAudio.delaySec > 0) {
                args.push('-ss', extAudio.delaySec.toString());
            }
            args.push('-i', extAudioName);
        }

        // 4. Handle External Subtitle Tracks
        for (let j = 0; j < externalSubtitles.length; j++) {
            const extSub = externalSubtitles[j];
            const extSubName = `sub_ext_${j}_${extSub.file.name.replace(/[^a-zA-Z0-9._-]/g, '_')}`;
            await worker.write(extSubName, new Uint8Array(await extSub.file.arrayBuffer()));
            args.push('-i', extSubName);
        }

        // 5. Apply Video Resolution Scaling Filter
        let scaleFilter = '';
        if (resSelect.value === 'custom') {
            const w = widthInput.value || 1920;
            const h = heightInput.value || 1080;
            scaleFilter = `scale=${w}:${h}`;
        } else if (resSelect.value !== 'source') {
            const [w, h] = resSelect.value.split('x');
            scaleFilter = `scale=${w}:${h}`;
        }

        if (scaleFilter) {
            args.push('-vf', scaleFilter);
        }

        // 6. Apply Video Bitrate & Audio Mute / Removal Logic
        if (['mp3', 'wav', 'flac'].includes(targetExt)) {
            args.push('-vn'); // Audio-only extraction
        } else {
            args.push('-b:v', bitrateSelect.value);
        }

        if (muteAudioCheck.checked || (!includeOriginalAudio && externalAudio.length === 0)) {
            args.push('-an'); // Mute / Remove All Audio
            log('Audio stream removed (-an)');
        } else {
            args.push('-b:a', audioBitrateSelect.value);
        }

        // Auto-match duration if external tracks added
        if (externalAudio.length > 0) {
            args.push('-shortest');
        }

        // Output file
        args.push(outputName);

        log(`Running FFmpeg WebAssembly Command: ffmpeg ${args.join(' ')}`);
        statusMessage.textContent = 'Transcoding via WebAssembly engine...';

        // Execute FFmpeg Transcode Command
        await worker.run(...args);

        // 7. Read Output File from VFS
        log('Transcoding complete! Reading converted file from WebAssembly memory...');
        const { data } = await worker.read(outputName);
        const mimeTypes = {
            mp4: 'video/mp4', mkv: 'video/x-matroska', webm: 'video/webm',
            avi: 'video/x-msvideo', mov: 'video/quicktime', flv: 'video/x-flv',
            ts: 'video/mp2t', mp3: 'audio/mp3', wav: 'audio/wav', flac: 'audio/flac'
        };

        const blob = new Blob([data.buffer], { type: mimeTypes[targetExt] || 'video/mp4' });
        const downloadUrl = URL.createObjectURL(blob);

        // Update Download Link & Filename
        downloadBtn.href = downloadUrl;
        downloadBtn.download = outputName;
        downloadBtn.style.display = 'inline-flex';

        if (!['mp3', 'wav', 'flac'].includes(targetExt)) {
            outputVideo.src = downloadUrl;
            outputVideo.style.display = 'block';
        }

        progressBarFill.style.width = '100%';
        progressText.textContent = '100%';
        statusMessage.textContent = '🎉 Transcoding completed successfully!';
        log(`🎉 File successfully saved as "${outputName}"! Click Download Result to save.`);

        // Cleanup VFS
        await worker.remove(inputName);
        await worker.remove(outputName);

    } catch (err) {
        log(`Transcoding error: ${err.message}`, true);
        statusMessage.textContent = 'Transcoding failed. Check terminal log.';
    } finally {
        startBtn.disabled = false;
    }
});
